Librarian/ViewModels/BrowseViewModel.cs
using Librarian.Controllers;
using System;
using System.Collections.Generic;

namespace Librarian.Models
{
    public class BrowseFileViewModel
    {
        public string Name { get; set; } = null!;

        public string Path { get; set; } = null!;

        public bool IsDirectory { get; set; }

        public DateTimeOffset LastModified { get; set; }

        public string? MimeType { get; set; }

        public long? Size { get; set; }

        public string? DisplaySize { get; set; }

        public string IconUrl { get; set; } = null!;
    }

    public class BrowseViewModel
    {
        public string Path { get; set; } = null!;

        public string DisplayName { get; set; } = null!;

        public string DisplayPath { get; set; } = null!;

        public string? ParentPath { get; set; }

        public IEnumerable<BrowseFileViewModel> Files { get; set; } = null!;

        // name, path
        public IEnumerable<(string, string)> Breadcrumbs { get; set; } = null!;

        public BrowseClipboardModel? Clipboard { get; set;}
    }
}

Librarian/Controllers/BrowseController.cs
using Librarian.Models;
using Librarian.Services;
using Librarian.Utils;
using Librarian.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using Microsoft.Extensions.Logging;
using MimeMapping;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using System.Text.Json;

namespace Librarian.Controllers
{
    public class BrowseController : Controller
    {
        private readonly ILogger<BrowseController> logger;
        readonly FileService fileService;

        const string BrowseClipboardKey = "browseClipboard";

        public BrowseController(ILogger<BrowseController> logger, FileService fileService)
        {
            this.logger = logger;
            this.fileService = fileService;
        }

        private IEnumerable<BrowseFileViewModel> GetFiles(string dirPath)
        {
            DirectoryInfo dirInfo = new(dirPath);

            var directories = dirInfo.EnumerateDirectories()
                .OrderBy(x => x.Name, new NaturalComparer());

            foreach (var dir in directories)
            {
                yield return new BrowseFileViewModel()
                {
                    Name = dir.Name,
                    Path = fileService.GetRelativePath(dir.FullName),
                    Size = null,
                    DisplaySize = null,
                    LastModified = dir.LastWriteTimeUtc,
                    IsDirectory = true,
                    MimeType = null,
                    IconUrl = Url.Content(IconMapping.FolderIcon)
                };
            }

            var files = dirInfo.EnumerateFiles()
                .OrderBy(x => x.Name, new NaturalComparer());

            foreach (var file in files)
            {
                string fileName = file.Name;
                string mime = MimeUtility.GetMimeMapping(fileName);

                yield return new BrowseFileViewModel()
                {
                    Name = fileName,
                    Path = fileService.GetRelativePath(file.FullName),
                    Size = file.Length,
                    DisplaySize = HumanizeUtils.HumanizeSize(file.Length),
                    LastModified = file.LastWriteTimeUtc,
                    IsDirectory = false,
                    MimeType = mime,
                    IconUrl = Url.Content(IconMapping.GetIconUrl(fileName, mime))
                };
            }
        }

        public IActionResult Index(string path)
        {
            try
            {
                string diskPath = fileService.Resolve(path);

                if (System.IO.File.Exists(diskPath))
                {
                    return this.InlineFileFromDisk(diskPath);
                }
                else
                {
                    DirectoryInfo directoryInfo = new(diskPath);

                    var vm = new BrowseViewModel
                    {
                        DisplayName = directoryInfo.Name,
                        DisplayPath = fileService.GetRelativePath(diskPath),
                        ParentPath = (directoryInfo.Parent != null && !fileService.IsRoot(diskPath))
                            ? fileService.GetRelativePath(directoryInfo.Parent.FullName)
                            : null,
                        Path = fileService.GetRelativePath(diskPath),
                        Files = GetFiles(diskPath),
                        Clipboard = GetClipboard()
                    };

                    if (vm.DisplayPath == ".")
                    {
                        vm.DisplayName = "Home";
                        vm.DisplayPath = "Home";
                    }

                    vm.Breadcrumbs = BuildBreadcrumbs(vm.Path);
                    return View(vm);
                }
            }
            catch (ArgumentException ex)
            {
                logger.LogError(ex, "Bad request!");
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Error handling request!");
                return StatusCode(500, ex.Message);
            }
        }

        private static IEnumerable<(string, string)> BuildBreadcrumbs(string path)
        {
            StringBuilder sb = new();
            if (path == ".")
            {
                yield break;
            }

            foreach (var element in path.Split('/'))
            {
                sb.Append(element);
                sb.Append('/');

                yield return (element, sb.ToString().TrimEnd('/'));
            }
        }

        [HttpPost]
        public IActionResult Cut([FromBody] BrowseCutRequest cutRequest)
        {
            // Validate request
            try
            {
                // Validate source is a valid directory
                cutRequest.Path.ValidateNotNull("No path provided!");

                var diskPath = fileService.Resolve(cutRequest.Path);
                if (!Directory.Exists(diskPath))
                    throw new ArgumentException("Path doesn't exist on disk!");

                // Validate items to cut
                cutRequest.Items.ValidateNotEmpty("No items provided!");
                foreach (var item in cutRequest.Items)
                {
                    item.ValidateFileName("Invalid item " + item);
                }

                // Add to clipboard
                SetClipboard(new BrowseClipboardModel()
                {
                    Move = true,
                    SourceFiles = cutRequest.Items.Select(x => cutRequest.Path + "/" + x).ToArray()
                });

                return Json(new { message = "OK" });
            }
            catch (Exception ex)
            {
                if (ex is ArgumentException || ex is PathTooLongException)
                    Response.StatusCode = StatusCodes.Status400BadRequest;
                else if (ex is SecurityException)
                    Response.StatusCode = StatusCodes.Status403Forbidden;
                else
                    Response.StatusCode = StatusCodes.Status500InternalServerError;
                logger.LogError(ex, "Error handling request!");
                return Json(new { message = ex.Message });
            }
        }

        [HttpPost]
        public IActionResult Copy([FromBody] BrowseCopyRequest copyRequest)
        {
            // Validate request
            try
            {
                // Validate source is a valid directory
                copyRequest.Path.ValidateNotNull("No path provided!");

                var diskPath = fileService.Resolve(copyRequest.Path);
                if (!Directory.Exists(diskPath))
                    throw new ArgumentException("Path doesn't exist on disk!");

                // Validate items to cut
                copyRequest.Items.ValidateNotEmpty("No items provided!");
                foreach (var item in copyRequest.Items)
                {
                    item.ValidateFileName("Invalid item " + item);
                }

                // Add to clipboard
                SetClipboard(new BrowseClipboardModel()
                {
                    Move = false,
                    SourceFiles = copyRequest.Items.Select(x => copyRequest.Path + "/" + x).ToArray()
                });

                return Json(new { message = "OK" });
            }
            catch (Exception ex)
            {
                if (ex is ArgumentException || ex is PathTooLongException)
                    Response.StatusCode = StatusCodes.Status400BadRequest;
                else if (ex is SecurityException)
                    Response.StatusCode = StatusCodes.Status403Forbidden;
                else
                    Response.StatusCode = StatusCodes.Status500InternalServerError;
                logger.LogError(ex, "Error handling request!");
                return Json(new { message = ex.Message });
            }
        }

        private BrowseClipboardModel? GetClipboard()
        {
            string? clipboardItemsStr = HttpContext.Session.GetString(BrowseClipboardKey);
            if (clipboardItemsStr == null)
                return null;

            return JsonSerializer.Deserialize<BrowseClipboardModel>(clipboardItemsStr);
        }

        private void SetClipboard(BrowseClipboardModel? content)
        {
            if (content != null)
            {
                string serialized = JsonSerializer.Serialize(content);
                HttpContext.Session.SetString(BrowseClipboardKey, serialized);
            }
            else
            {
                HttpContext.Session.Remove(BrowseClipboardKey);
            }
        }

        [HttpPost]
        public IActionResult Paste([FromBody] BrowsePasteRequest pasteRequest)
        {
            // Validate request
            try
            {
                // Validate source is a valid directory
                pasteRequest.Path.ValidateNotNull("No path provided!");

                var clipboard = GetClipboard();
                clipboard.ValidateNotNull("Nothing to paste!!!");

                // Call backend to perform file operation
                if (clipboard!.Move)
                    fileService.MoveFiles(clipboard.SourceFiles, pasteRequest.Path);
                else fileService.CopyFiles(clipboard.SourceFiles, pasteRequest.Path);

                // Clear clipboard
                SetClipboard(null);

                return Json(new { message = "OK" });
            }
            catch (Exception ex)
            {
                if (ex is ArgumentException || ex is PathTooLongException)
                    Response.StatusCode = StatusCodes.Status400BadRequest;
                else if (ex is SecurityException)
                    Response.StatusCode = StatusCodes.Status403Forbidden;
                else
                    Response.StatusCode = StatusCodes.Status500InternalServerError;

Librarian/Controllers/MetadataController.cs
using Librarian.Services;
using Librarian.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Librarian.Controllers
{
    public class MetadataController : Controller
    {
        private readonly ILogger<MetadataController> logger;
        readonly FileService fileService;
        readonly MetadataService metadataService;

        public MetadataController(ILogger<MetadataController> logger, MetadataService metadataService, FileService fileService)
        {
            this.logger = logger;
            this.metadataService = metadataService;
            this.fileService = fileService;
        }

        public async Task<IActionResult> IndexAsync(string path)
        {
            try
            {
                var vm = new MetadataViewModel();

                string diskPath = fileService.Resolve(path);

                FileSystemInfo fsInfo;
                if (System.IO.File.Exists(diskPath))
                {
                    fsInfo = new FileInfo(diskPath);
                    vm.IsDirectory = false;

                    var parent = ((FileInfo)fsInfo).Directory;
                    vm.ParentPath = parent != null ? fileService.GetRelativePath(parent.FullName) : null;
                }
                else if (Directory.Exists(diskPath))
                {
                    fsInfo = new DirectoryInfo(diskPath);
                    vm.IsDirectory = true;
                }
                else
                {
                    logger.LogError("File not found: {}", diskPath);
                    return NotFound("File not found!");
                }

                vm.DisplayName = fsInfo.Name;
                vm.Path = fileService.GetRelativePath(diskPath);

                vm.DisplayPath = fileService.GetRelativePath(diskPath);
                if (vm.DisplayPath == ".")
                {
                    vm.DisplayName = "Home";
                    vm.DisplayPath = "Home";
                }

                // collect and fill metadata
                var allMetadata = await metadataService.CollectMetadataAsync(diskPath).ToListAsync();
                vm.Metadata = allMetadata.Where(x => x.SubResource == null);
                vm.SubResourceMetadata = allMetadata
                    .Where(x => x.SubResource != null)
                    .GroupBy(x => x.SubResource!)
                    .ToDictionary(grouping => grouping.Key, grouping => grouping.ToArray().AsEnumerable());

                return View(vm);
            }
            catch (ArgumentException ex)
            {
                logger.LogError(ex, "Bad request!");
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Error handling request!");
                return StatusCode(500, ex.Message);
            }
        }
    }
}

Librarian/Views/Browse/Index.cshtml
@using Librarian.Utils;
@model BrowseViewModel
@{
    ViewData["Title"] = Model.DisplayPath;
    ViewData["CurrentPage"] = "browse";

    bool buttonUpEnabled = (Model.ParentPath != null);
    string? buttonUpUrl = buttonUpEnabled
        ? Url.Action("Index", "Browse", new { path = Model.ParentPath })
        : "#";
}

@section Scripts {
    <script>
        document.librarian_browse_path = "@Model.Path";
        document.librarian_browse_urlCut = "@Url.Action("Cut", "Browse")";
        document.librarian_browse_urlCopy = "@Url.Action("Copy", "Browse")";
        document.librarian_browse_urlPaste = "@Url.Action("Paste", "Browse")";
        document.librarian_browse_urlRename = "@Url.Action("Rename", "Browse")";
        document.librarian_browse_urlRenameBulk = "@Url.Action("RenameBulk", "Browse")";
        document.librarian_browse_urlDelete = "@Url.Action("Delete", "Browse")";
        document.librarian_browse_urlMetadata = "@(Url.Action("Index", "Metadata"))/@(Model.Path)";
    </script>

    <script src="~/js/browse.js" asp-append-version="true"></script>
}

<div class="window">
    <div class="window-title">
        <div class="window-title-inner">
            <h1>Browsing @Model.DisplayName</h1>
        </div>
    </div>

    <div class="menubar">
        <ul>
            <li>
                File
                    <ul>
                        <li>New</li>
                        <li>Open</li>
                    </ul>
            </li>
            <li>Edit</li>
            <li>Help
                <ul>
                    <li>About...</li>
                </ul>
            </li>
        </ul>
    </div>

    <hr />

    <div class="toolbar">
        <button id="btn-cut"><img src="~/icons/32/edit-cut.png" />Cut</button>
        <button id="btn-copy"><img src="~/icons/32/edit-copy.png" />Copy</button>
        <button id="btn-paste" disabled="@(Model.Clipboard == null)"><img src="~/icons/32/edit-paste.png" />Paste</button>
        <div class="separator"></div>
        <button id="btn-rename"><img src="~/icons/32/edit.png" />Rename</button>
        <button id="btn-delete"><img src="~/icons/32/edit-delete.png" />Delete</button>
        <div class="separator"></div>
        <button id="btn-metadata"><img src="~/icons/32/gnome-stock-insert-table.png" />Metadata</button>
    </div>

    <hr />

    <div class="toolbar">
        <a class="toolbar-button @HtmlUtils.BoolToClass(!buttonUpEnabled, "disabled")"
           href="@buttonUpUrl">
           <img src="~/icons/16/go-up.png" />
        </a>
        <div class="input location-bar">
            <a class="toolbar-button"
               href="@Url.Action("Index", "Browse", new { path = "" })">
                <img src="~/icons/16/go-home.png" />
            </a>
            <span>/</span>
            @foreach (var (name, path) in Model.Breadcrumbs)
            {
                <a class="toolbar-button" href="@Url.Action("Index", "Browse", new { path = path })">@name</a>
                <span>/</span>
            }
        </div>
    </div>

    <div class="window-content">

        <table id="file-listing" class="file-listing sortable">
            <thead>
                <tr>
                    <th><input id="chk-select-all" type="checkbox" /></th>
                    <th data-col="icon"></th>
                    <th>File</th>
                    <th>Size</th>
                    <th>Type</th>
                    <th>Last modified</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var file in Model.Files)
                {
                    <tr class="file-entry" data-id="@(file.Name)">
                        <td><input id="chk-selected" type="checkbox" /></td>
                        <td><img src="@file.IconUrl"></td>
                        @if (file.IsDirectory)
                        {
                            <td data-sort="0_@(file.Name)">
                                <a href="@Url.Action("Index", "Browse", new { path = file.Path})">@(file.Name)</a>
                            </td>
                            <td></td>
                            <td>&lt;DIR&gt;</td>
                        }
                        else
                        {
                            <td data-sort="1_@(file.Name)">
                                <a href="@Url.Action("Index", "Browse", new { path = file.Path})">@(file.Name)</a>
                            </td>
                            <td data-sort="@(file.Size)">@(file.DisplaySize)</td>
                            <td>@(file.MimeType)</td>
                        }

                        <td>@(file.LastModified.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss"))</td>
                        <td>
                            @if (file.Name != "..")
                            {
                                <a href="@Url.Action("Index", "Browse", new { path = file.Path})">Properties [todo]</a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>

    <div class="window-statusbar">
        <div id="msg-status" class="flex-fill">Ready</div>
        <div>
            @{
                var clipboardTitle = "Clipboard empty.";
                if (Model.Clipboard != null)
                    clipboardTitle = string.Format("{0} item{1} {2} in clipboard",
                                          Model.Clipboard.SourceFiles.Length,
                                          Model.Clipboard.SourceFiles.Length > 1 ? "s" : "",
                                          Model.Clipboard.Move ? "cut" : "copied");
            }
            <img id="img-clipboard-indicator"
                 src="~/icons/16/icon-clipboard.png"
                 title="@clipboardTitle"
                 class="@HtmlUtils.BoolToClass(Model.Clipboard == null, "disabled")"/></div>
    </div>

</div>